- hosts: all 
  remote_user: daniel
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install OG
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - zsh
      - build-essential
      - git
      - vim
      - aptitude
      - python
      - dconf-cli
      - uuid-runtime
      - cmake
      - python3-venv

# Zsh

  - name: Change shell to zsh
    user:
      name: daniel
      shell: /usr/bin/zsh
    become: yes

  - name: Download oh-my-zsh
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/install-zsh.sh
      owner: daniel
      group: daniel
      mode: 0755

  - name: Execute oh-my-zsh
    shell: /tmp/install-zsh.sh --unattended
    args:
      # chdir: /tmp
      executable: /bin/sh
    ignore_errors: yes


# Docker installation
  - name: Install docker required system packages
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Add daniel to docker group
    become: yes
    user:
      name: daniel
      append: yes
      groups: docker

# Install docker-compose
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
    become: yes

# Install Vundle
  - name: Install Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      clone: yes
      dest: /home/daniel/.vim/bundle/Vundle.vim

# Install Dotfiles
  - name: Clone Dotfiles
    git:
      repo: https://github.com/danielmoore-info/dotfiles.git
      clone: yes
      dest: /home/daniel/dotfiles

  - name: Copy zshrc to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/zshrc
      dest: /home/daniel/.zshrc
 
  - name: Copy vimrc to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/vimrc
      dest: /home/daniel/.vimrc

  - name: Copy tmux.conf to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/tmux.conf
      dest: /home/daniel/.tmux.conf

# Github based tools
 
  - name: Clone theHarvester
    git:
      repo: https://github.com/laramies/theHarvester.git
      clone: yes
      dest: /opt/theHarvester
    become: yes
 
# Dirsearch
 
  - name: Clone dirsearch
    git:
      repo: https://github.com/maurosoria/dirsearch.git
      clone: yes
      dest: /opt/dirsearch
    become: yes
 
  - name: create dirsearch symlink
    file:
      src: /opt/dirsearch/dirsearch.py
      dest: /usr/local/bin/dirsearch
      state: link
    become: yes
 
# Interlace
  
  - name: Clone interlace
    git:
      repo: https://github.com/codingo/Interlace.git
      clone: yes
      dest: /opt/Interlace
    become: yes
 
  - name: Clone sublister
    git:
      repo: https://github.com/aboul3la/Sublist3r.git
      clone: yes
      dest: /opt/Sublister
    become: yes
 
# sqlmap download and install
  - name: Clone sqlmap
    git:
      repo: https://github.com/sqlmapproject/sqlmap.git
      clone: yes
      depth: 1
      dest: /opt/sqlmap-dev
    become: yes
 
  - name: make sqlmap.py executable
    file:
      path: /opt/sqlmap-dev/sqlmap.py
      mode: '0755'
    become: yes
 
  - name: create sqlmap symlink
    file:
      src: /opt/sqlmap-dev/sqlmap.py
      dest: /usr/local/bin/sqlmap
      state: link
    become: yes
 
# Metasploit
  - name: Download metasploit installer
    get_url:
      url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
      dest: /tmp/msfinstall
      owner: daniel
      group: daniel
      mode: 0755
 
  - name: Execute metasploit installer
    shell: /tmp/msfinstall
    args:
      executable: /bin/sh
    become: yes
 
  - name: Clone exploitdb
    git:
      repo: https://github.com/offensive-security/exploitdb.git
      clone: yes
      dest: /opt/exploitdb
    become: yes

# Download BurpSuite
  - name: Download Burpsuite
    get_url:
      url: https://raw.githubusercontent.com/danielmoore-info/UbuntuPentestAnsible/master/burpsuite_pro_linux_v1_7_35.sh
      dest: /home/daniel/burpsuite_pro_linux_v1_7_35.sh
      owner: daniel
      group: daniel
      mode: 0755
 
# # - name: Edit exploitdb config
# #   command: sed 's|path_array+=(.*)|path_array+=("/opt/exploitdb")|g' /opt/exploitdb/.searchsploit_rc > ~/.searchsploit_rc
# #   args:
# #     warn: false
#
# # - name: Copy searchsploit to path
# #   command: ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit
# #   become: yes
