- hosts: localhost 
  remote_user: daniel
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install OG
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - zsh
      - build-essential
      - git
      - vim
      - aptitude
      - python
      - dconf-cli 
      - uuid-runtime
      - python3-venv

  - name: Install vscode
    snap:
      name: code
      classic: yes
    become: yes

# Zsh

  - name: Change shell to zsh
    user:
      name: daniel
      shell: /usr/bin/zsh
    become: yes

  - name: Download oh-my-zsh
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/install-zsh.sh
      owner: daniel
      group: daniel
      mode: 0755

  - name: Execute oh-my-zsh
    shell: /tmp/install-zsh.sh --unattended
    args:
      # chdir: /tmp
      executable: /bin/sh
    ignore_errors: yes

# Install NodeJS

  - name: Download NodeJS Setup Script
    get_url:
      url: https://deb.nodesource.com/setup_12.x
      dest: /tmp/setup_12.x
      owner: daniel
      group: daniel
      mode: 0755

  - name: Run NodeJS Setup Script
    shell: /tmp/setup_12.x
    args:
      executable: /bin/bash
    become: yes

  - name: Install NodeJS via APT
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - nodejs

# Docker installation
  - name: Install docker required system packages
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Add daniel to docker group
    become: yes
    user:
      name: daniel
      append: yes
      groups: docker

# Install docker-compose
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
    become: yes

# Install Vundle
  - name: Install Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      clone: yes
      dest: /home/daniel/.vim/bundle/Vundle.vim

# Install Dotfiles
  - name: Clone Dotfiles
    git:
      repo: https://github.com/danielmoore-info/dotfiles.git
      clone: yes
      dest: /home/daniel/dotfiles

  - name: Copy zshrc to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/zshrc
      dest: /home/daniel/.zshrc
 
  - name: Copy vimrc to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/vimrc
      dest: /home/daniel/.vimrc

  - name: Copy tmux.conf to correct location
    copy:
      remote_src: yes
      src: /home/daniel/dotfiles/tmux.conf
      dest: /home/daniel/.tmux.conf

