- hosts: ubuntu*
  remote_user: daniel
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install OG
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - zsh
      - build-essential
      - vim
      - aptitude

# Zsh

  - name: Change shell to zsh
    user:
      name: daniel
      shell: /usr/bin/zsh
    become: yes

  - name: Download oh-my-zsh
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/install-zsh.sh
      owner: daniel
      group: daniel
      mode: 0755

  - name: Execute oh-my-zsh
    command: chdir=/tmp sh install-zsh.sh
    ignore_errors: yes

# Docker installation
  - name: Install docker required system packages
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Add daniel to docker group
    become: yes
    user:
      name: daniel
      append: yes
      groups: docker

# Github based tools

  - name: Clone theHarvester
    git:
      repo: https://github.com/laramies/theHarvester.git
      clone: yes
      dest: /opt/theHarvester
    become: yes

  - name: Clone dirsearch
    git:
      repo: https://github.com/maurosoria/dirsearch.git
      clone: yes
      dest: /opt/dirsearch
    become: yes
  
  - name: Clone interlace
    git:
      repo: https://github.com/codingo/Interlace.git
      clone: yes
      dest: /opt/Interlace
    become: yes

  - name: Clone sublister
    git:
      repo: https://github.com/aboul3la/Sublist3r.git
      clone: yes
      dest: /opt/Sublister
    become: yes

  - name: Clone sqlmap
    git:
      repo: https://github.com/sqlmapproject/sqlmap.git
      clone: yes
      depth: 1
      dest: /opt/sqlmap-dev
    become: yes

  - name: Clone exploitdb
    git:
      repo: https://github.com/offensive-security/exploitdb.git
      clone: yes
      dest: /opt/exploitdb
    become: yes

  # - name: Edit exploitdb config
  #   command: sed 's|path_array+=(.*)|path_array+=("/opt/exploitdb")|g' /opt/exploitdb/.searchsploit_rc > ~/.searchsploit_rc
  #   args:
  #     warn: false

  # - name: Copy searchsploit to path
  #   command: ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit
  #   become: yes